server:
  port: 8080

spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2:3b
  datasource:
    url: jdbc:mysql://localhost:3306/speakai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver